### ISSUE TITLE
Link external website in sidebar menu

### ISSUE THREAD

**Issue by makeavish** [alxshelepenok/gatsby-starter-lumen#616]
**Is your feature request related to a problem? Please describe.**
I want to add an external link to my CV website. I want that link to appear as a sidebar menu.

**Describe alternatives you've considered**
I tried to edit add menu.js [https://spectrum.chat/gatsby-js/general/how-to-use-gatsby-link-for-external-links~282768c9-1995-415b-b576-b419c2cd0199](url). But I wasn't successful. 
Can someone please help?

**Additional context**

**Comment by sparklesam** [comment]
The reason why it does not work is Link component does not support external links. In order to solve this, you can create a new component e.g. GatsbyLink so it can parse both internal and external links. Follow [this tutorial](https://www.gatsbyjs.org/docs/gatsby-link/#reminder-use-link-only-for-internal-links). ( `import React from "react"` is missing at the first line.)

After that, update the `config.js` to add the link
```
{
 label: "Resume",
 path: "https://google.com"
}
```

And also replace the Link component from gatsby to the new component

` import { Link } from "gatsby";`
to
` import Link from "../../GatsbyLink"`

This should solve your problem.

**Comment by makeavish** [comment]
It works now!
@sparklesam Thanks for your help!
