### ISSUE TITLE
changing config.postsPerPage doesn't take effect

### ISSUE THREAD

**Issue by Leshgan** [alxshelepenok/gatsby-starter-lumen#660]
When change postsPerPage in config.js from 4 to 10 number of posts in page still 4. Pagination crashes.

**Comment by NiallRees** [comment]
Did you overcome this @Leshgan ? I'm having the same issue

**Comment by Kamigami55** [comment]
@Leshgan @NiallRees I'm also facing this issue. Do you guys have any solution? thx.

**Comment by Kamigami55** [comment]
I finally changed postsPerPage from 4 to 10.

In addition to change the number of postsPerPage in **/config.js**,

```js
'use strict';

module.exports = {
  // ...
  postsPerPage: 10,
  // ...
};
```

you have to add postsLimit type to PageContext by modify **/src/types/index.js**,

```js
// ...
export type PageContext = {
  tag: string,
  category: string,
  currentPage: number,
  prevPagePath: string,
  nextPagePath: string,
  hasPrevPage: boolean,
  hasNextPage: boolean,
  postsLimit: number // <--- add this
};
// ...
```

so that postsLimit prop can be passed from **create-posts-pages.js** to **index-template.js**.

But I still don't know why the default value of postsLimit is 4, btw.
