### ISSUE TITLE
Deploy to Netlify gets "Error pushing to remote repository"

### ISSUE THREAD

**Issue by j7an** [alxshelepenok/gatsby-starter-lumen#695]
**Describe the bug**
When deploying starter to Netlify via the Deploy button in README, the deploy fails with "Error pushing to remote repository"

**To Reproduce**
1. Go to repo web URL "https://github.com/alxshelepenok/gatsby-starter-lumen"
2. Click on 'Deploy to Netlify' button
3. On Netlify click the current deploy to see details
4. At end of deploy there will be an error reading “Error pushing to remote repository”
5. Go to created repo on Github. It was created but empty.

**Expected behavior**
Deployment should push repo to personal Github repo.

**Additional context**
This seems related to main.workflow file which Github prevents from being modified/pushed to repo as seen here: https://community.netlify.com/t/error-pushing-to-remote-repository/1252/3

**Comment by Abraham21** [comment]
I have the same issue.

**Comment by Abraham21** [comment]
For those wondering how I was able to get around the issue, the easy Netlify deployment button was not working. 
I had to 
1. create a repo and push my changes manually after running `gatsby new blog https://github.com/alxshelepenok/gatsby-starter-lumen`. 
2. setup netlify with the new repo. 
3. It will still fail with the following error visible in the Netlify logs `command failed with exit code 127 yarn build`
4. install the gatsby-cli in the project using `npm install gatsby-cli --save`. 
5. change the netlify.toml file to use `gatsby build` instead of `yarn build`. 
6. make sure the build command in the Netlify deploy settings matches your netlify.toml file (`gatsby build`) and make sure you have pushed your changes from the earlier steps
7. CI/CD should redeploy the project successfully, or you can try to trigger a deploy from Netlify

The easy deploy gave me the same error as this issue, so I cannot comment on solving that. However, I could achieve the deployment and CI/CD by following the above.

**Comment by Triskae** [comment]
I'm also having this issue !

**Comment by olafgoj** [comment]
I'm getting the same issue. Site is visible via netlify link to my page, but GitHub repo is empty.
