### ISSUE TITLE
Hot reloading not working with hanges in config.js on develop

### ISSUE THREAD

**Issue by iamioannis** [alxshelepenok/gatsby-starter-lumen#746]
**Describe the bug**
While I am editing config.js to customise the website while on Gatsby develop, changes are not visible with hot reloading after saving. In order to work I have to stop and start develop again.

Is this the way it is supposed to work?
Note: When i am editing content under content hot reload works.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run Gatsby develop 
2. Edit config.js (eg. title:)
3. Save config.js
4. Browser doesn't refresh and reflect changes 

**Expected behavior**
Browser should refresh when changing making changes in config.js. (If not designed otherwise)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser: Firefox
 - Version 81.0b4 (64-bit)

**Comment by trinwin** [comment]
I'm having the same issue

**Comment by payamazadi** [comment]
I did a little bit of research and it looks like the HMR (Hot Module Reloading) only works for changes to gatsby-config.js. There are ways to rig it up so that other files will cause updates too, but it doesn't seem to be easy, at least, I didn't spend much time with it. Here's a link: https://github.com/gatsbyjs/gatsby/issues/21938

**Comment by Kayx23** [comment]
The issue is explained here as well #711
