### ISSUE TITLE
Marking pagination pages as 'noindex'

### ISSUE THREAD

**Issue by n-k-d** [alxshelepenok/gatsby-starter-lumen#821]
Currently all pagination pages like 'site.com/page/1' are indexed on google as 'Indexed, not submitted in sitemap'. Is there a way to mark them 'noindex' ?

**Comment by Jeffreyhung** [comment]
You can use plugins like [Gatsby-plugin-sitemap](https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/) to create a more customized sitemap.
It has the option to specify the links you want to exclude.

**Comment by nkaushikd** [comment]
That will only remove the urls from sitemap. But google and other search engine will crawl other pages like /page/1, /category/x , tag/x etc and show them in search. Which is bad for SEO. I fixed it using React Helmet.

**Comment by Jeffreyhung** [comment]
If you have a sitemap in place, search engines will probably look for your sitemap.xml files and use them as a reference.
Alternatively, you can use tools like [netlify-plugin-submit-sitemap](netlify-plugin-submit-sitemap) to proactively submit your sitemap to search engines.
Also, you can use robot.txt to tell search engines pages you don't what them to index.

Anyhow, congrats on fixing it, maybe you can share how you fix it so that in the future if someone else has the same issues they can use your solution as a reference.

**Comment by payamazadi** [comment]
@nkaushikd is right, those pages should be noindex, nofollow by default - specifically, 
`<meta name="robots" content="noindex, nofollow">`

You can go into the proper template file, and add a prop for Layout like
`noIndex={true}`

And then in Layout you can do conditional rendering:
`let noIndexMeta;
  if(noIndex) {
    noIndexMeta = <meta name="robots" content="noindex, nofollow" />
  }

...

return (
    <div className={styles.layout}>
      <Helmet>
        ..
        {noIndexMeta}
      </Helmet>
      {children}
    </div>
`
