### ISSUE TITLE
Dependency issue, unable to install starter. 

### ISSUE THREAD

**Issue by magink** [alxshelepenok/gatsby-starter-lumen#887]
**Describe the bug**
`gatsby new blog https://github.com/alxshelepenok/gatsby-starter-lumen`
  fails with 
`ERESOLVE unable to resolve dependency tree`

**To Reproduce**
1. Run `gatsby new blog https://github.com/alxshelepenok/gatsby-starter-lumen` in user Projects folder

**Expected behavior**
Starter should install. 

**Terminal output**

```bash
gatsby new blog https://github.com/alxshelepenok/gatsby-starter-lumen
info Creating new site from git:
https://github.com/alxshelepenok/gatsby-starter-lumen.git

Cloning into 'blog'...
remote: Enumerating objects: 340, done.
remote: Counting objects: 100% (340/340), done.
remote: Compressing objects: 100% (271/271), done.
remote: Total 340 (delta 47), reused 301 (delta 43), pack-reused 0
Receiving objects: 100% (340/340), 4.88 MiB | 1.03 MiB/s, done.
success Created starter directory layout
info Installing packages...

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gatsby-starter-lumen@3.0.7
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!   peer react@"^16.4.2 || ^17.0.0" from gatsby-link@2.10.0
npm ERR!   node_modules/gatsby-link
npm ERR!     gatsby-link@"^2.10.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"15.x || 16.x || 16.4.0-alpha.0911da3" from @reach/router@1.3.4
npm ERR! node_modules/@reach/router
npm ERR!   peer @reach/router@"^1.3.3" from gatsby-link@2.10.0
npm ERR!   node_modules/gatsby-link
npm ERR!     gatsby-link@"^2.10.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\magink\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:

 ERROR

Command failed with exit code 1: npm install



  Error: Command failed with exit code 1: npm install

  - error.js:56 makeError
    [npm]/[gatsby-cli]/[execa]/lib/error.js:56:11

  - index.js:114 handlePromise
    [npm]/[gatsby-cli]/[execa]/index.js:114:26

  - task_queues:94 processTicksAndRejections
    node:internal/process/task_queues:94:5

  - init-starter.js:135 install
    [npm]/[gatsby-cli]/lib/init-starter.js:135:7

  - init-starter.js:202 clone
    [npm]/[gatsby-cli]/lib/init-starter.js:202:3

  - init-starter.js:343 initStarter
    [npm]/[gatsby-cli]/lib/init-starter.js:343:5

  - create-cli.js:485
    [npm]/[gatsby-cli]/lib/create-cli.js:485:9
```
**Desktop (please complete the following information):**
 - OS: Windows 10 and Debian 10.7.0. Same issue on both
 - Git Bash: 4.4.23(1)-release
 - Node: v15.6.0
 - Gatsby-cli: 2.18.0 

**Additional context**
Tried on my host Windows 10 and also on a fresh install of Debian 10.7.0  in Virtualbox, only dev environment installed.

**Comment by libelink** [comment]
I had the same issue, I just updated npm and now there is a problem with dependencies. I don't know how to resolve it but I was able to install the starter using yarn instead of npm as my Gatsby package manager. There is still some errors now (I think it is the same as #881) but I was able to install it.
Here is a [reference](https://www.gatsbyjs.com/docs/glossary/yarn/) to change from npm to yarn

**Comment by magink** [comment]
> I had the same issue, I just updated npm and now there is a problem with dependencies. I don't know how to resolve it but I was able to install the starter using yarn instead of npm as my Gatsby package manager. There is still some errors now (I think it is the same as #881) but I was able to install it.
> Here is a [reference](https://www.gatsbyjs.com/docs/glossary/yarn/) to change from npm to yarn

Tried yarn but didn't help help getting the Starter running. It seems a bot has issued lots of pull request with the dependency updates but the repo owner has not/does not accept them. Is there any way I can get the new pull requests added to my local repo?

**Comment by talatkuyuk** [comment]
I have the same issue. It does not run since the same dependency issue. (it seems related with Gatsby-link ?)

**Comment by krasney** [comment]
Has anyone found a workaround for this?

**Comment by datapolitical** [comment]
Same issue. If this project is still maintained, making it installable seems like it should be a high priority. @alxshelepenok any ideas what's going on here?

**Comment by rkabrick** [comment]
Same problem still. Sad, really liked the template. Will try to find other blog templates in the meantime

**Comment by hossam-zaki** [comment]
I also have the same problem. Any help here?

**Comment by hossam-zaki** [comment]
So, I've spent a few hours on this and arrived at the following. 

First step, downgrade to node version 12. Then follow the instructions in the readme. 

You'll then get an error when trying to run the build, so then follow this: https://github.com/alxshelepenok/gatsby-starter-lumen/issues/913 


This worked for me!

**Comment by jduran7** [comment]
I'm experiencing the same issue. I'm trying to install the template using Windows 10 WSL , node version 12.22.0

**Comment by safiulanik** [comment]
The recommended way to setup your build environment on Windows is to install the **windows-build-tools** package by running `npm install --global windows-build-tools --vs2015`

If this doesn't work for you, there is further information (including troubleshooting) in the official [Gatsby on Windows docs](https://www.gatsbyjs.org/docs/gatsby-on-windows/).

**Comment by abbaselmas** [comment]
below is a netlify build log, problem is npm version.
"The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0"."

------------------------------------
12:05:43 PM: Build ready to start
12:05:45 PM: build-image version: 6a1f7e52d9cf33642526245391bde1af7845fc53 (xenial)
12:05:45 PM: build-image tag: v3.10.0
12:05:45 PM: buildbot version: 15524a3b58bf754f0d39869e5258d4b3f3eeeb5b
12:05:45 PM: Fetching cached dependencies
12:05:45 PM: Failed to fetch cache, continuing with build
12:05:45 PM: Starting to prepare the repo for build
12:05:45 PM: No cached dependencies found. Cloning fresh repo
12:05:45 PM: git clone https://github.com/abbaselmas/gatsby-starter-lumen
12:05:51 PM: Preparing Git Reference refs/heads/main
12:05:51 PM: Parsing package.json dependencies
12:05:52 PM: Starting build script
12:05:52 PM: Installing dependencies
12:05:52 PM: Python version set to 2.7
12:05:53 PM: v12.18.0 is already installed.
12:05:54 PM: Now using node v12.18.0 (npm v6.14.4)
12:05:54 PM: Started restoring cached build plugins
12:05:54 PM: Finished restoring cached build plugins
12:05:54 PM: Attempting ruby version 2.7.1, read from environment
12:05:55 PM: Required ruby-2.7.1 is not installed - installing.
12:05:56 PM: Searching for binary rubies, this might take some time.
12:05:56 PM: Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/16.04/x86_64/ruby-2.7.1.tar.bz2
12:05:56 PM: Checking requirements for ubuntu.
12:05:56 PM: Requirements installation successful.
12:05:57 PM: ruby-2.7.1 - #configure
12:05:57 PM: ruby-2.7.1 - #download
12:05:57 PM: ruby-2.7.1 - #validate archive
12:06:03 PM: ruby-2.7.1 - #extract
12:06:05 PM: ruby-2.7.1 - #validate binary
12:06:06 PM: ruby-2.7.1 - #setup
12:06:07 PM: ruby-2.7.1 - #gemset created /opt/buildhome/.rvm/gems/ruby-2.7.1@global
12:06:07 PM: ruby-2.7.1 - #importing gemset /opt/buildhome/.rvm/gemsets/global.gems........................................
12:06:08 PM: ruby-2.7.1 - #generating global wrappers........
12:06:08 PM: ruby-2.7.1 - #gemset created /opt/buildhome/.rvm/gems/ruby-2.7.1
12:06:08 PM: ruby-2.7.1 - #importing gemsetfile /opt/buildhome/.rvm/gemsets/default.gems evaluated to empty gem list
12:06:08 PM: ruby-2.7.1 - #generating default wrappers........
12:06:09 PM: Using /opt/buildhome/.rvm/gems/ruby-2.7.1
12:06:09 PM: Using ruby version 2.7.1
12:06:10 PM: Using PHP version 5.6
12:06:10 PM: Started restoring cached yarn cache
12:06:10 PM: Finished restoring cached yarn cache
12:06:10 PM: Installing yarn at version 1.3.2
12:06:10 PM: Installing Yarn!
12:06:10 PM: > Downloading tarball...
12:06:10 PM: [1/2]: https://yarnpkg.com/downloads/1.3.2/yarn-v1.3.2.tar.gz --> /tmp/yarn.tar.gz.4maR9W98tY
12:06:10 PM:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
12:06:10 PM:                                  Dload  Upload   Total   Spent    Left  Speed
12:06:10 PM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
12:06:10 PM: 100    77  100    77    0     0    432      0 --:--:-- --:--:-- --:--:--   435
12:06:10 PM: 100    91  100    91    0     0    164      0 --:--:-- --:--:-- --:--:--   164
12:06:11 PM: 100   624  100   624    0     0    708      0 --:--:-- --:--:-- --:--:--   708
12:06:11 PM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
12:06:11 PM: 100  865k  100  865k    0     0   776k      0  0:00:01  0:00:01 --:--:-- 5771k
12:06:11 PM: [2/2]: https://yarnpkg.com/downloads/1.3.2/yarn-v1.3.2.tar.gz.asc --> /tmp/yarn.tar.gz.4maR9W98tY.asc
12:06:11 PM: 100    81  100    81    0     0   2037      0 --:--:-- --:--:-- --:--:--  2037
12:06:11 PM: 100    95  100    95    0     0   1386      0 --:--:-- --:--:-- --:--:--  1386
12:06:11 PM: 100   628  100   628    0     0   3704      0 --:--:-- --:--:-- --:--:--  3704
12:06:11 PM: 100  1027  100  1027    0     0   4600      0 --:--:-- --:--:-- --:--:--  4600
12:06:11 PM: > Verifying integrity...
12:06:11 PM: gpg: Signature made Thu 02 Nov 2017 04:44:10 PM UTC using RSA key ID FD2497F5
12:06:11 PM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
12:06:11 PM: gpg: Note: This key has expired!
12:06:11 PM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
12:06:11 PM:      Subkey fingerprint: 6A01 0C51 6600 6599 AA17  F081 46C2 130D FD24 97F5
12:06:11 PM: > GPG signature looks good
12:06:11 PM: > Extracting to ~/.yarn...
12:06:11 PM: > Adding to $PATH...
12:06:11 PM: > Successfully installed Yarn 1.3.2! Please open another terminal where the `yarn` command will now be available.
12:06:12 PM: No yarn workspaces detected
12:06:12 PM: Started restoring cached node modules
12:06:12 PM: Finished restoring cached node modules
12:06:12 PM: Installing NPM modules using Yarn version 1.3.2
12:06:13 PM: yarn install v1.3.2
12:06:13 PM: (node:3192) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
12:06:13 PM: [1/4] Resolving packages...
12:06:14 PM: [2/4] Fetching packages...
12:06:54 PM: info fsevents@2.3.2: The platform "linux" is incompatible with this module.
12:06:54 PM: info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
12:06:54 PM: info fsevents@1.2.13: The platform "linux" is incompatible with this module.
12:06:54 PM: info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
12:06:54 PM: error array-move@4.0.0: The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0".
12:06:54 PM: error Found incompatible module
12:06:54 PM: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
12:06:54 PM: Error during Yarn install
12:06:54 PM: Build was terminated: Build script returned non-zero exit code: 1
12:06:54 PM: Creating deploy upload records
12:06:54 PM: Failing build: Failed to build site
12:06:54 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
12:06:54 PM: Finished processing build request in 1m9.267898866s

**Comment by liuyang1520** [comment]
Using `npm i --legacy-peer-deps` still doesn't work for me. Have to use `yarn` instead:
- Open `~/.config/gatsby/config.json`
- Update to
```json
	"cli": {
		"packageManager": "yarn"
	},
```

**Comment by allergictobullshit** [comment]
> Same problem still. Sad, really liked the template. Will try to find other blog templates in the meantime

Me too, did you find any similar templates?

**Comment by alxshelepenok** [comment]
Thank you for your feedback. The starter has been updated to the new version and the bug has probably been fixed.
